webpack_encore:
    output_path: '%kernel.project_dir%/public/build'
    script_attributes:
        defer: true
    builds:
        page: '%kernel.project_dir%/public/build/page'
        dashboard: '%kernel.project_dir%/public/build/dashboard'
